import { Theme } from 'theme-ui'

export const theme: Theme = {
    breakpoints: ['40em', '47.5em', '61.5em', '64em'],
    fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
    colors: {
        text: '#040405',
        textSecondary: 'rgba(4, 4, 5, 0.5)',
        textButton: '#040405',
        textButtonActive: '#FFF',
        borderColor: 'rgba(4, 4, 5, 0.1)',
        borderHoverColor: 'rgba(4, 4, 5, 0.2)',
        placeHolder: 'rgba(4, 4, 5, 0.2)',
        background: '#FFF',
        backgroundButton: '#FFF',
        backgroundButtonActive: '#1f1f1f',
        backgroundYellow: 'rgba(254, 218, 3, 0.1)',
        hover: 'rgba(4, 4, 5, 0.05)',
        primary: '#0066ff',
        red: '#ff5757',
        toggleButtonOff: 'rgba(45, 129, 255, 0.1)',
        toggleButtonOn: 'rgba(45, 129, 255)',
        toggleCircle: '#FFF',
        modes: {
            dark: {
                text: '#FFF',
                textSecondary: 'rgba(255, 255, 255, 0.5)',
                textButton: '#FFF',
                textButtonActive: '#040405',
                borderColor: 'rgba(255, 255, 255, 0.1)',
                borderHoverColor: 'rgba(255, 255, 255, 0.2)',
                placeHolder: 'rgba(255, 255, 255, 0.2)',
                background: '#121212',
                backgroundButton: '#1f1f1f',
                backgroundButtonActive: '#FFF',
                backgroundYellow: 'rgba(255, 255, 255, 0.1)',
                hover: 'rgba(255, 255, 255, 0.05)',
                toggleButtonOff: 'rgba(45, 129, 255, 0.3)',
                toggleButtonOn: 'rgba(45, 129, 255)',
                toggleCircle: '#111',
            },
        },
    },
    space: [0, 4, 8, 16, 32, 64, 128, 256],
    radii: [6, 16, 24, 32, 40, 48],
    fontWeights: {
        body: 500,
        semiBold: 600,
        bold: 700,
        heavy: 900,
    },
    lineHeights: {
        body: 1.5,
        heading: 1.25,
    },
    shadows: {
        small: '0 0 4px rgba(0, 0, 0, 0.125)',
        large: '0 0 24px rgba(0, 0, 0, 0.125)',
    },
    text: {
        heading: {
            fontFamily: 'sans-serif',
            lineHeight: 'heading',
            fontWeight: 'bold',
        },
    },
    forms: {
        input: {
            border: 'none',
            borderRadius: 0,
            py: 14,
            color: 'textSecondary',
            fontSize: 1,
            fontWeight: 'semiBold',
            ':focus': {
                outline: 'none',
            },
            '::placeholder': {
                color: 'textSecondary',
            },
        },
        footerInput: {
            color: 'textButton',
            border: 'none',
            background: '#FFF',
            height: '100%',
            fontWeight: 'bold',
            fontSize: 1,
            ':focus': {
                outline: 'none',
            },
            '::placeholder': {
                color: 'placeHolder',
            },
        },
    },
    buttons: {
        border: {
            display: 'flex',
            flexFlow: 'row nowrap',
            height: 40,
            cursor: 'pointer',
            backgroundColor: 'transparent',
            color: 'textButton',
            borderRadius: 4,
            transition: 'all 0.12s ease-in-out 0s',
            px: 22,
            minWidth: 'auto',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 1,
            fontWeight: 'heavy',
            border: '1px solid',
            borderColor: 'borderColor',
            lineHeight: '16px',
            ':hover': {
                borderColor: 'borderHoverColor',
            },
            ':focus': {
                outline: 'none',
            },
            ':active': {
                transform: 'scale(0.95)',
            },
        },
        borderActive: {
            display: 'flex',
            flexFlow: 'row nowrap',
            height: 40,
            cursor: 'pointer',
            backgroundColor: 'backgroundButtonActive',
            color: 'textButtonActive',
            borderRadius: 4,
            border: '1px rgba(4, 4, 5, 0.1) solid',
            transition: 'all 0.12s ease-in-out 0s',
            px: 22,
            minWidth: 'auto',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 1,
            fontWeight: 'heavy',
            lineHeight: '16px',
            ':hover': {
                border: '1px rgba(4, 4, 5, 0.28) solid',
            },
            ':focus': {
                outline: 'none',
            },
            ':active': {
                transform: 'scale(0.95)',
            },
        },
        primary: {
            display: 'flex',
            flexFlow: 'row nowrap',
            height: 48,
            cursor: 'pointer',
            backgroundColor: 'primary',
            borderRadius: 5,
            transition: 'all 0.12s ease-in-out 0s',
            px: 26,
            minWidth: 'auto',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: 15,
            fontWeight: 'heavy',
            ':hover': {
                backgroundColor: 'rgba(0, 102, 255, 0.95)',
                color: 'rgba(255,255,255,0.9)',
            },
            ':focus': {
                outline: 'none',
            },
            ':active': {
                transform: 'scale(0.95)',
            },
            ':disabled': {
                bg: 'borderColor',
            },
        },
        secondary: {
            display: 'flex',
            flexFlow: 'row nowrap',
            backgroundColor: 'rgba(0, 102, 255, 0.15)',
            color: 'primary',
            height: 40,
            px: 22,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: 4,
            fontSize: 1,
            fontWeight: 'heavy',
            transition: 'all 0.12s ease-in-out 0s',
            cursor: 'pointer',
            ':hover': {
                color: 'rgba(0, 102, 255, 0.9)',
                backgroundColor: 'rgba(0, 102, 255, 0.2)',
            },
            ':focus': {
                outline: 'none',
            },
            ':active': {
                transform: 'scale(0.95)',
            },
        },
        circle: {
            px: 10,
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'center',
            borderRadius: '50%',
            width: 40,
            height: 40,
            transition: 'all 0.12s ease-in-out 0s',
            color: 'text',
            backgroundColor: 'background',
            border: '1px solid',
            borderColor: '#aaa',
            cursor: 'pointer',
            ':hover': {
                border: '1px #ccc solid',
            },
            ':focus': {
                outline: 'none',
            },
            ':active': {
                transform: 'scale(0.95)',
            },
        },
    },
    images: {
        avatar: {
            width: 38,
            height: 38,
            borderRadius: 9999,
            xxs: {
                width: 16,
                height: 16,
            },
            xs: {
                width: 26,
                height: 26,
            },
            sm: {
                width: 48,
                height: 48,
            },
            md: {
                width: 64,
                height: 64,
            },
            lg: {
                width: 68,
                height: 68,
            },
            xl: {
                width: 120,
                height: 120,
            },
        },
        background: {
            height: 100,
        },
    },
}
