import { alpha } from '@theme-ui/color'

export default {
    breakpoints: ['40em', '52em', '64em'],
    fontSizes: [12, 14, 16, 20, 24, 32, 48, 64],
    colors: {
        text: '#040405',
        textSecondary: alpha('text', 0.5),
        background: '#fff',
        hover: alpha('text', 0.05),
        primary: '#0066ff',
        red: '#ff5757',
        modes: {
            dark: {
                text: '#fff',
                textSecondary: alpha('white', 0.5),
                background: '#1f1f1f',
                hover: alpha('white', 0.05),
            },
        },
    },
    space: [0, 4, 8, 16, 32, 64, 128, 256],
    fontWeights: {
        body: 400,
        heading: 700,
        bold: 700,
    },
    lineHeights: {
        body: 1.5,
        heading: 1.25,
    },
    shadows: {
        small: '0 0 4px rgba(0, 0, 0, .125)',
        large: '0 0 24px rgba(0, 0, 0, .125)',
    },
    variants: {},
    text: {
        heading: {
            fontFamily: 'sans-serif',
            lineHeight: 'heading',
            fontWeight: 'heading',
        },
    },
    buttons: {
        primary: {
            display: 'flex',
            flexFlow: 'row nowrap',
            height: '48px',
            cursor: 'pointer',
            backgroundColor: 'primary',
            borderRadius: 48,
            transition: 'all 0.12s ease-in-out 0s',
            paddingLeft: '26.4px',
            paddingRight: '26.4px',
            paddingTop: '0',
            paddingBottom: '0',
            minWidth: 'auto',
            alignItems: 'center',
            justifyContent: 'center',
            fontSize: '15px',
            fontWeight: '900',
            fontFamily: 'inherit',
            transformOrigin: 'center center',
            userSelect: 'none',
            ':hover': {
                backgroundColor: alpha('primary', 0.95),
                color: alpha('white', 0.9),
            },
            ':focus': {
                outline: 'none',
            },
        },
        secondary: {
            display: 'flex',
            flexFlow: 'row nowrap',
            backgroundColor: alpha('primary', 0.15),
            color: 'primary',
            height: '40px',
            paddingLeft: '22px',
            paddingRight: '22px',
            paddingTop: '0',
            paddingBottom: '0',
            minWidth: 'auto',
            border: '1px solid transparent',
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: '40px',
            fontSize: '14px',
            fontWeight: '900',
            fontFamily: 'inherit',
            transition: 'all 0.12s ease-in-out 0s',
            transformOrigin: 'center center',
            userSelect: 'none',
            cursor: 'pointer',
            ':hover': {
                color: alpha('primary', 0.9),
                backgroundColor: alpha('primary', 0.2),
            },
            ':focus': {
                outline: 'none',
            },
        },
    },
    images: {
        xs: {
            width: 26,
            height: 26,
            objectFit: 'cover',
            borderRadius: 9999,
        },
        sm: {
            width: 48,
            height: 48,
            objectFit: 'cover',
            borderRadius: 9999,
        },
        md: {
            width: 64,
            height: 64,
            objectFit: 'cover',
            borderRadius: 9999,
        },
        lg: {
            width: 68,
            height: 68,
            borderRadius: 9999,
            objectFit: 'cover',
        },
        xl: {
            width: 120,
            height: 120,
            borderRadius: 9999,
            objectFit: 'cover',
        },
        background: {
            height: 100,
            objectFit: 'cover',
        },
    },
}
